spring.application.name=api-gateway
server.port=8080

# Eureka Server Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable Gateway service discovery through Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
